### ISSUE TITLE
Android Basics: Lemonade app

### ISSUE THREAD

**Issue by JIMMYN1X** [google-developer-training/android-basics-kotlin-lemonade-app#46]
I'm trying to do the lemonade codelabe, after I load the file in android studio. and try to use activity_main.xml nothing happens it just loads. I also get the error that the version of gradle isn't up to date and also it doesn't recognize gradle at times as well, I'm not sure how to proceed please help

**Comment by adrian-best** [comment]
Edit: Try downloading the most recent version of android studio. I was able to open up the project with no problems and no wonky workarounds. Ensure you update the android sdk when the popup comes too.

I found a workaround to this. If you can build other projects (such as your dice roller app from the previous code labs), take the gradle-related files and use those instead of the ones that come with the lemonade app.

In hindsight I should have just figured out how to update my gradle files¯\_(ツ)_/¯

**Comment by mostafaSamir33** [comment]
open gradle project and change the gradle to 7.2.2

![2022-12-06](https://user-images.githubusercontent.com/118981102/205982888-b4a50efb-1bc3-416b-a7b4-f5835804bc36.png)
